### ISSUE TITLE
This looks awesome!

### ISSUE THREAD

**Issue by shyndman** [vanesyan/jetlog.dart#16]
I've been looking for an alternative to the logging package, and this is it! Thanks!

**Comment by segfaultmedaddy** [comment]
Thanks man! I really appreciate it!

There are a couple of changes need to be done for the library itself, but I expect 'em to be non-breaking changes, like support for `Map`s, `List`s, etc. as well as more handlers (btw there are a couple of issues for 'em).

**Comment by segfaultmedaddy** [comment]
I'll close it as it is not an issue itself. But again thanks a lot man! 😄

**Comment by 0xDazzer** [comment]
Awesome job, dude!
